services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: ids.web
        network_mode: host
        extra_hosts:
            - "redis:127.0.0.1"
            - "backend:127.0.0.1"
        restart: always
    
    redis:
        image: redis
        container_name: ids.redis
        network_mode: host
        extra_hosts:
            - "web:127.0.0.1"
            - "backend:127.0.0.1"
        restart: always

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: ids.backend
        network_mode: "host"
        extra_hosts:
            - "web:127.0.0.1"
            - "redis:127.0.0.1"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 500M
                reservations:
                    cpus: '0.25'
                    memory: 250M
        restart: always

